module.exports = {
  reactSidebar: [
    {
      type: 'category',
      label: 'React',
      items: [{ type: 'autogenerated', dirName: 'react' }],
    },
  ],
  helperSidebar: [
    {
      type: 'category',
      label: '函数',
      items: [{ type: 'autogenerated', dirName: 'helper' }],
    },
  ],
}
