const directories = require('./directories')

let count = 1
const sidebars = directories.reduce((side, { sidebars }) => {
  // https://docusaurus.io/zh-CN/docs/next/sidebar/multiple-sidebars
  // 当浏览其中某个文件时，对应的侧边栏会被显示
  side[`sidebar-${count++}`] = sidebars.map(({ label, dirName }) => ({
    type: 'category',
    label,
    items: [{ type: 'autogenerated', dirName }],
  }))

  return side
}, {})

module.exports = {
  ...sidebars,
}
