import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      label: '网络',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'internet' }],
    },
    {
      label: 'HTML',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'html' }],
    },
    {
      label: 'CSS',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'css' }],
    },
    {
      label: 'JS',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'js' }],
    },
    {
      label: 'React',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'react' }],
    },
    {
      label: '工程化',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'engineering' }],
    },
    {
      label: '安全',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'security' }],
    },
  ],

  roadmap: [
    'roadmap/frontend/index',
    {
      label: 'Internet',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'roadmap/frontend/internet' }],
    },
    {
      label: 'CSS',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'roadmap/frontend/css' }],
    },
  ],

  code: [{ type: 'autogenerated', dirName: 'code' }],
}

export default sidebars
