import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      label: 'HTTP',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'http' }],
    },
    {
      label: 'CSS',
      type: 'category',
      items: [{ type: 'autogenerated', dirName: 'css' }],
    },
  ],
}

export default sidebars
