// const directories = require('./directories')
const fs = require('fs')
// 为了取消缓存，实现 directories 更新后刷新页面
const directories = JSON.parse(fs.readFileSync('./directories.json'))

let count = 1
const sidebars = directories.reduce((side, { sidebars }) => {
  // https://docusaurus.io/zh-CN/docs/next/sidebar/multiple-sidebars
  // 当浏览其中某个文件时，对应的侧边栏会被显示
  side[`sidebar-${count++}`] = sidebars.map(({ label, dirName }) => {
    // 有 label，意味着需要分类汇总
    if (label) {
      return {
        type: 'category',
        label,
        items: [{ type: 'autogenerated', dirName }],
      }
    }
    // 否则，直接平铺文章
    return { type: 'autogenerated', dirName }
  })

  return side
}, {})

module.exports = {
  ...sidebars,
}
